name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image Results
      working-directory: ./result
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Build the Docker image Vote
      working-directory: ./vote
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      
